version: '3' 
services: 
 
  frontend:
    # image: placar-ups_frontend:latest
    build:
      context: ./containers/frontend/ 
    container_name: placar-frontend
    ports: 
      - "8080:80"      
    networks: 
      - app-network 
  
networks: 
  app-network: 
    driver: bridge
